name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  CI: true 

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Setup environment
        uses: actions/setup-node@v3.2.0
        with: 
          node-version: 18
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      
      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build libs and test-app
        run: yarn build

      - name: Unit tests
        run: yarn test

      - name: Setup e2e
        run: npx playwright install --with-deps
      
      - name: e2e
        run: yarn --cwd packages/test-e2e test:ci

      - name: Archive E2E artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-results
          path: packages/test-e2e/*/test-results/**/*.png
          if-no-files-found: ignore

